# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fppnxjLvKGH3grjcAd49I4YY4RN54Kas
"""

# ==============================================================================
# CELL 1: SETUP AND DATA UPLOAD (8-INPUT VERSION)
# ==============================================================================
print("--- Starting Step 1: Setup ---")

# 1. Install Libraries
print("Installing libraries...")
!pip install stable-baselines3[extra] gymnasium pandas > /dev/null
print("Libraries installed.")

# 2. Import Libraries
import pandas as pd
import io
import os
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from google.colab import files

# 3. Upload Data
print("\nPlease upload your 'cleaned_drone_data.csv' file.")
print("Make sure it contains these columns: front, back, left, right, top, roll, pitch, yaw")

try:
    uploaded = files.upload()
    file_name = next(iter(uploaded))
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))

    # Quick check to ensure columns exist
    required_cols = ['front', 'back', 'left', 'right', 'top', 'roll', 'pitch', 'yaw']
    if not all(col in df.columns for col in required_cols):
        print(f"❌ ERROR: Your CSV is missing one of these columns: {required_cols}")
        print("Please fix your CSV and re-run this cell.")
        raise ValueError("Missing columns")

    print(f"✅ Dataset '{file_name}' loaded successfully!")
    print(df[required_cols].head())

except Exception as e:
    print(f"❌ Error: {e}")
    raise

# ==============================================================================
# CELL 2: ENVIRONMENT DEFINITIONS (8-INPUT)
# ==============================================================================

class DroneEnv8(gym.Env):
    """
    The base environment using 8 inputs:
    5 Distance Sensors + 3 Orientation states (Roll, Pitch, Yaw)
    """
    def __init__(self, dataframe):
        super(DroneEnv8, self).__init__()
        self.df = dataframe

        # --- INPUTS: 8 Columns ---
        self.observations = self.df[['front', 'back', 'left', 'right', 'top', 'roll', 'pitch', 'yaw']].values.astype(np.float32)

        # --- OUTPUTS: 3 Actions ---
        self.expert_actions = self.df[['roll', 'pitch', 'yaw']].values.astype(np.float32)

        # Action space: 3 continuous values (-1 to 1)
        self.action_space = spaces.Box(low=-1, high=1, shape=(3,), dtype=np.float32)

        # Observation space: 8 continuous values
        # We use -inf to inf because Roll/Pitch can be negative
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(8,), dtype=np.float32)
        self.current_step = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step = 0
        return self.observations[self.current_step], {}

    def step(self, action):
        expert_action = self.expert_actions[self.current_step]
        error = np.mean((action - expert_action)**2)
        reward = float(-error)

        is_at_end = self.current_step >= len(self.df) - 2
        terminated = is_at_end
        truncated = False

        self.current_step += 1
        obs_index = min(self.current_step, len(self.df) - 1)
        next_observation = self.observations[obs_index]

        return next_observation, reward, terminated, truncated, {}

class NoisyDroneEnv8(DroneEnv8):
    """
    Smart Noise:
    - High Noise for Distance Sensors (Lasers are glitchy)
    - Low Noise for IMU (Gyro is smooth)
    """
    def __init__(self, dataframe, sensor_noise=10.0, imu_noise=0.05):
        super().__init__(dataframe)
        self.sensor_noise = sensor_noise
        self.imu_noise = imu_noise
        print(f"Robust Env Created: Sensor Noise={sensor_noise}, IMU Noise={imu_noise}")

    def _add_noise(self, observation):
        # 1. Noise for first 5 items (Distance)
        s_noise = np.random.normal(0, self.sensor_noise, size=5)

        # 2. Noise for last 3 items (Roll/Pitch/Yaw)
        i_noise = np.random.normal(0, self.imu_noise, size=3)

        # 3. Combine
        full_noise = np.concatenate([s_noise, i_noise])

        noisy_obs = observation + full_noise

        # Clip only the distances (first 5) to be positive
        noisy_obs[:5] = np.maximum(0, noisy_obs[:5])

        return noisy_obs.astype(np.float32)

    def reset(self, seed=None, options=None):
        initial_obs, info = super().reset(seed=seed)
        return self._add_noise(initial_obs), info

    def step(self, action):
        next_obs, reward, term, trunc, info = super().step(action)
        return self._add_noise(next_obs), reward, term, trunc, info

print("✅ 8-Input Environments Defined.")

# ==============================================================================
# CELL 3: TRAIN AND DOWNLOAD
# ==============================================================================
print("--- Starting Training ---")
model_path = "/content/ppo_drone_robust_8input.zip"

try:
    # 1. Initialize the Smart Noisy Environment
    train_env = NoisyDroneEnv8(df, sensor_noise=10.0, imu_noise=0.05)

    # 2. Create Model
    model = PPO("MlpPolicy", train_env, verbose=1)

    # 3. Train
    print("Training in progress... (100,000 steps)")
    model.learn(total_timesteps=100_000)

    # 4. Save and Download
    model.save(model_path)
    print("✅ Training Complete.")
    print(f"Downloading {model_path}...")
    files.download(model_path)

except Exception as e:
    print(f"❌ Training Failed: {e}")